class_name ENUMS

#Mech Types
#Mech Theme
#Mech Status
#Pilot Theme
#Pilot Status
#Odds Criteria
#Mission Flavor Type
#Mission Status
#Environments (Location Types)
#Part Type (Equipable or Not)
#Part Status

enum MECH_TYPE {
	UNDECIDED = -1,
	DEFENSIVE = 0,
	AERIAL = 1,
	SPECIAL_OPS = 2,
	UNDERWATER = 3,
	SPACE = 4,
	EXTREME_TEMP = 5,
	LONG_HAUL = 6,
	HAND_TO_HAND = 7,
	HIGH_GRAVITY = 8,
	ANTI_CORROSIVE = 9,
	RACING = 10,
}

enum MECH_THEME {
	UNDECIDED = -1,
	RED = 0,
	BLUE = 0,
	DARK = 0,
}

enum MECH_STATUS {
	UNDECIDED = -1,
	FOR_SALE = 0,
	IN_GARAGE = 1,
	ON_MISSION = 2,
	NOT_AVAILABLE =3,
	DESTROYED=4
}

enum RETURN_CRITERIA {
	UNDECIDED = -1,
	RETURN_CRITERIA_0 =0,
	RETURN_CRITERIA_1 =1,
	RETURN_CRITERIA_2 =2,
	RETURN_CRITERIA_3 =3,
	RETURN_CRITERIA_4 =4,
	RETURN_CRITERIA_5 =5,
	RETURN_CRITERIA_6 =6,
	RETURN_CRITERIA_7 =7,
	RETURN_CRITERIA_8 =8,
	RETURN_CRITERIA_9 =9
}
enum MISSION_CRITERIA {
	UNDECIDED = -1,
	MISSION_CRITERIA_0 =0,
	MISSION_CRITERIA_1 =1,
	MISSION_CRITERIA_2 =2,
	MISSION_CRITERIA_3 =3,
	MISSION_CRITERIA_4 =4,
	MISSION_CRITERIA_5 =5,
	MISSION_CRITERIA_6 =6,
	MISSION_CRITERIA_7 =7,
	MISSION_CRITERIA_8 =8,
	MISSION_CRITERIA_9 =9
}

enum MISSION_FLAVOR_TYPE {
	UNDECIDED = -1,
	RESCUE = 0,
	DESTROY = 1,
	DELIVERY = 2
}

enum MISSION_STATUS {
	UNDECIDED = -1,
	LOCKED = 0,
	UNLOCKED = 1,
	IN_PROGRESS = 2,
	SUCCESS = 3,
	FAILED = 4,
	NEEDS_DEBRIEF = 5
}


enum ENVIRONMENT {
	UNDECIDED = -1,
	DESERT = 0,
	SWAMP = 1,
	URBAN = 2,
	JUNGLE = 3,
	SPACE = 4,
	UNDERWATER_FROZEN = 5,
	UNDERWATER = 6,
	UNDERWATER_BOILING = 7,
	ICY = 8,
	UNDERGROUND = 9,
	ACID_LAKE = 10,
}

enum PART_TYPE {
	UNDECIDED = -1,
	NOT_EQUIPABLE =0,
	EQUIPABLE = 1,
	#CONSUMABLE = 2
}

enum PART_STATUS {
	UNDECIDED = -1,
	FOR_SALE = 0,
	PURCHASED = 1,
	EQUIPT = 2,
	NOT_AVAILABLE = 3, #Destroyed, sold or recycled.

}

enum PART_THEME{
	UNDECIDED = -1,
	RED =0,
	BLUE =0,

}
enum PILOT_STATUS{
	UNDECIDED = -1,
	FOR_HIRE = 0,
	HIRED = 1,
	ON_MISSION = 2,
	DEAD = 3,
	NOT_AVAILABLE_YET=4
}
enum PILOT_THEME{
	UNDECIDED = -1,
	RED_FEMALE = 0,
	BLUE_FEMALE = 1,
	RED_MALE = 2,
	BLUE_MALE = 3
}


enum VOICEMAIL_STATUS{
	UNDECIDED = -1,
	LOCKED=0,
	UNHEARD=1,
	HEARD=2
}
