class_name ENUMS


enum MECH_TYPE {
	UNDECIDED = -1,
	DEFENSIVE = 0,
	AERIAL = 1,
	SPECIAL_OPS = 2,
	UNDERWATER = 3,
	SPACE = 4,
	EXTREME_TEMP = 5,
	LONG_HAUL = 6,
	ANTI_CORROSIVE = 7,
	HIGH_GRAVITY = 8,
	RACING = 9,
	ANY_TYPE = 10
}

enum MECH_THEME {
	UNDECIDED = -1,
	RED = 0,
	BLUE = 1,
	DARK = 2
}

enum MECH_STATUS {
	UNDECIDED = -1,
	FOR_SALE = 0,
	IN_GARAGE = 1,
	ON_MISSION = 2,
	NOT_AVAILABLE =3,
	DESTROYED=4
}

enum RETURN_CRITERIA {
	UNDECIDED = -1,
	ADVANTAGE_UNDERWATER =0,
	ADVANTAGE_AERIAL =1,
	ADVANTAGE_IN_CITY =2,
	ADVANTAGE_SPECIAL_OPS =3,
	ADVANTAGE_ESCORT =4,
	ADVANTAGE_IN_SPACE =5,
	ADVANTAGE_IN_SWAMP =6,
	ADVANTAGE_IN_DESERT =7,
	ADVANTAGE_IN_EXTREME_TEMPERATURES =8,
	ADVANTAGE_RACING =9,
	NO_CRITERIA_FOR_ADVANTAGE=10,
	NO_ADVANTAGE_UNDERWATER=11

}
enum MISSION_CRITERIA {
	UNDECIDED = -1,
	ADVANTAGE_DURING_OFFENSIVE_COMBAT =0,
	ADVANTAGE_DURING_RESCUE =1,
	ADVANTAGE_DURING_DELIVERY =2,
	ADVANTAGE_DURING_ESCORT =3,
	ADVANTAGE_DURING_INTEL_GATHERING =4,
	ADVANTAGE_DURING_DEFENSIVE_COMBAT =5,
	ADVANTAGE_DURING_TRAVEL =6,
	ADVANTAGE_IN_SPACE =7,
	UNDERWATER_COMBAT_ADVANTAGE=8,
	ADVANTAGE_RACING =9,
	NO_CRITERIA_FOR_ADVANTAGE=10,
	ADVANTAGE_DURING_ANY_COMBAT=11,
	DRY_COMBAT_ADVANTAGE= 12
}

enum MISSION_FLAVOR_TYPE {
   UNDECIDED = -1,
	RESCUE = 0,
	DESTROY = 1,
	DELIVERY = 2,
	ESCORT = 3,
	INTEL_GATHERING=4,
	DEFEND=5
}

enum MISSION_STATUS {
	UNDECIDED = -1,
	LOCKED = 0,
	UNLOCKED = 1,
	IN_PROGRESS = 2,
	SUCCESS = 3,
	FAILED = 4,
	NEEDS_DEBRIEF = 5
}

enum ENVIRONMENT {
	UNDECIDED = -1,
	DESERT = 0,
	SWAMP = 1,
	URBAN = 2,
	JUNGLE = 3,
	SPACE = 4,
	UNDERWATER_FROZEN = 5,
	UNDERWATER = 6,
	UNDERWATER_BOILING = 7,
	ICY = 8,
	UNDERGROUND = 9,
	ACID_LAKE = 10,
	RACE_TRACK = 11
}

enum PART_TYPE {
	UNDECIDED = -1,
	NOT_EQUIPABLE =0,
	EQUIPABLE = 1,
	RACING=2
}

enum PART_STATUS {
	UNDECIDED = -1,
	FOR_SALE = 0,
	PURCHASED = 1,
	EQUIPT = 2,
	NOT_AVAILABLE = 3,
}

enum PART_THEME{
	UNDECIDED = -1,
	RED =0,
	BLUE =1
}

enum PILOT_STATUS{
	UNDECIDED = -1,
	FOR_HIRE = 0,
	HIRED = 1,
	ON_MISSION = 2,
	DEAD = 3,
	NOT_AVAILABLE_YET=4
}

enum PILOT_THEME{
	UNDECIDED = -1,
	RED_FEMALE = 0,
	BLUE_FEMALE = 1,
	RED_MALE = 2,
	BLUE_MALE = 3
}

enum VOICEMAIL_STATUS{
	UNDECIDED = -1,
	LOCKED=0,
	UNHEARD=1,
	HEARD=2
}
